# Generated by Django 5.2.6 on 2025-10-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='શીર્ષક (Title)')),
                ('description', models.TextField(blank=True, verbose_name='વર્ણન (Description)')),
                ('notice_type', models.CharField(choices=[('text', 'Text Notice'), ('image', 'Image Notice'), ('pdf', 'PDF Notice')], default='text', max_length=10, verbose_name='નોટિસ પ્રકાર (Notice Type)')),
                ('file', models.FileField(blank=True, help_text='Photo (JPG, PNG) અથવા PDF upload કરો', null=True, upload_to='uploads/', verbose_name='ફાઇલ (Photo/PDF)')),
                ('color', models.CharField(choices=[('note-yellow', 'Yellow'), ('note-pink', 'Pink'), ('note-green', 'Green'), ('note-white', 'White'), ('note-lined', 'Lined White')], default='note-yellow', max_length=20, verbose_name='રંગ (Color)')),
                ('pin_color', models.CharField(choices=[('pin-red', 'Red Pin'), ('pin-blue', 'Blue Pin'), ('pin-green', 'Green Pin'), ('pin-yellow', 'Yellow Pin')], default='pin-red', max_length=20, verbose_name='પિન રંગ (Pin Color)')),
                ('expiry_date', models.DateField(verbose_name='સમાપ્તિ તારીખ (Expiry Date)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='બનાવ્યું (Created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='અપડેટ કર્યું (Updated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='સક્રિય છે? (Active)')),
            ],
            options={
                'verbose_name': 'નોટિસ (Notice)',
                'verbose_name_plural': 'નોટિસ (Notices)',
                'ordering': ['-created_at'],
            },
        ),
    ]
