# Generated by Django 5.2.6 on 2025-10-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('PGDCA', 'PGDCA')], default='BCA', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.CharField(choices=[('sem-1', 'Semester 1'), ('sem-3', 'Semester 3'), ('sem-5', 'Semester 5'), ('all', 'All Semesters')], default='sem-1', max_length=10),
        ),
    ]
