# Generated by Django 5.2.6 on 2025-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_department_notice_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Check this to make the notice appear on all department pages (બધા પેજ પર બતાવવા માટે આને ટિક કરો)'),
        ),
    ]
